[package]
name = "scriptpubkeys_per_block"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin_slices = { version = "0.9.1", features = ["bitcoin"] }
blocks_iterator = "2.1.0"
env_logger = "0.11.6"
log = "0.4.22"
